---
server:
  port: ${SERVER_PORT} # Порт приложения
---
saver:
  filepath: ${SAVER_FILEPATH}
---
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always
